apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pinning-service-api-hpa
  namespace: pinning-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pinning-service-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pinning-service-worker-hpa
  namespace: pinning-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pinning-service-worker
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60