environment: development

server:
  host: 0.0.0.0
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  shutdown_timeout: 10s

database:
  dsn: postgres://user:password@localhost:5432/pinning_db?sslmode=disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 1h

redis:
  url: redis://localhost:6379/0
  namespace: pinning_service

ipfs:
  api_url: http://localhost:5001
  gateway_url: http://localhost:8080
  timeout: 30s

filecoin:
  lotus_api: http://localhost:1234/rpc/v0
  lotus_token: ""
  wallet_address: ""
  min_deal_duration: 518400  # ~6 months in epochs

pricing:
  base_price_per_gb_per_month: 0.001  # FIL
  markup_percentage: 20.0
  minimum_deal_size: 1048576  # 1MB

workers:
  concurrency: 5

jwt:
  secret: "your-jwt-secret-change-in-production"
  expiration: 24h

rate_limit:
  requests_per_minute: 100
  burst: 20

logging:
  level: info
  format: json
